#Buna ziua domnule profesor!

for x in range(0, 36):
    print("Hello World!")

#Sau.. : 

#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")
#print("Hello World!")